#define LEADER    QK_LEAD

#define _____     KC_TRANSPARENT

#define TO_BAS    TO(_BASE)
#define TO_SYM    TO(_SYMBOLS)
#define TO_ARR    TT(_ARROWS)
#define TO_MSE    TT(_MOUSE)
#define I3_MENU   LT(_SPECIAL,KC_MENU)

#define ARR_TAB   LT(_ARROWS, KC_TAB)
#define ARR_SPC   LT(_ARROWS, KC_SPC)
#define MOU_SPC   LT(_MOUSE, KC_SPC)
#define MOU_TAB   LT(_MOUSE, KC_TAB)
#define PAD_ENT   LT(_NUMBERS, KC_ENT)
#define PAD_DEL   LT(_NUMPAD, KC_DEL)
#define MED_ENT   LT(_MEDIA, KC_ENT)
#define SYM_ESC   LT(_SYMBOLS, KC_ESC)
#define NUM_RGHT  LT(_NUMBERS, KC_RIGHT)
#define SYM_BSP   LT(_SYMBOLS, KC_BSPC)
#define MED_ESC   LT(_MEDIA, KC_ESC)
#define SPE_LFT   LT(_SPECIAL, KC_LEFT)

#define A_2       ALT_T(KC_2)
#define A_3       ALT_T(KC_3)
#define A_5       ALT_T(KC_5)
#define A_8       ALT_T(KC_8)
#define A_COMM    ALT_T(KC_COMM)
#define A_D       ALT_T(KC_D)
#define A_DOT     ALT_T(KC_DOT)
#define A_F5      ALT_T(KC_F5)
#define A_F6      ALT_T(KC_F6)
#define A_K       ALT_T(KC_K)
#define A_P5      ALT_T(KC_P5)
#define A_QUOT    ALT_T(KC_QUOT)
#define A_QUOT    ALT_T(KC_QUOT)
#define A_RBRC    ALT_T(KC_RBRC)  
#define A_SLSH    ALT_T(KC_SLSH)
#define A_SLSH    ALT_T(KC_SLSH)
  
#define A_LEFT    LALT(KC_LEFT)
#define A_RGHT    LALT(KC_RIGHT)

#define C_1       CTL_T(KC_1)
#define C_4       CTL_T(KC_4)
#define C_7       CTL_T(KC_7)
#define C_COMM    CTL_T(KC_COMMA)
#define C_DOT     CTL_T(KC_DOT)
#define C_EQL     CTL_T(KC_EQL)
#define C_F       CTL_T(KC_F)
#define C_F5      CTL_T(KC_F5)
#define C_F6      CTL_T(KC_F6)
#define C_J       CTL_T(KC_J)
#define C_LBRK    CTL_T(KC_LBRK) 
#define C_P4      CTL_T(KC_P4)
#define C_LBRC    CTL_T(KC_LBRC)

#define C_ENT     LCTL(KC_ENT)
#define C_INS     LCTL(KC_INSERT)
#define C_TAB     LCTL(KC_TAB)
  
#define G_2       GUI_T(KC_2)
#define G_3       GUI_T(KC_3)
#define G_6       GUI_T(KC_6)
#define G_9       GUI_T(KC_9)
#define G_BSLS    GUI_T(KC_BSLS)
#define G_F4      GUI_T(KC_F4)
#define G_F7      GUI_T(KC_F7)
#define G_GRV     GUI_T(KC_GRV)
#define G_L       GUI_T(KC_L)
#define G_P6      GUI_T(KC_P6)
#define G_S       GUI_T(KC_S)
#define G_SC      GUI_T(KC_SCLN)
  
#define S_0       SFT_T(KC_0)
#define S_1       SFT_T(KC_1)
#define S_A       SFT_T(KC_A)
#define S_DOT     SFT_T(KC_DOT)
#define S_F8      SFT_T(KC_F8)
#define S_GRV     SFT_T(KC_GRV)
#define S_MINS    SFT_T(KC_MINS)
#define S_PMNS    SFT_T(KC_PMNS)
#define S_RBKT    SFT_T(KC_RBRC)
#define S_SC      SFT_T(KC_SCLN)
#define S_SLSH    SFT_T(KC_SLSH)
  
#define S_INS     LSFT(KC_INSERT)
#define SC_TAB    LCTL(LSFT(KC_TAB))
  
#define WM_0      LGUI(KC_F10)
#define WM_1      LGUI(KC_F1)
#define WM_2      LGUI(KC_F2)
#define WM_3      LGUI(KC_F3)
#define WM_4      LGUI(KC_F4)
#define WM_5      LGUI(KC_F5)
#define WM_6      LGUI(KC_F6)
#define WM_7      LGUI(KC_F7)
#define WM_8      LGUI(KC_F8)
#define WM_9      LGUI(KC_F9)
#define WM_D      LGUI(KC_D)
#define WM_DOWN   LGUI(KC_DOWN)
#define WM_E      LGUI(KC_E)
#define WM_ENT    LGUI(KC_ENT)
#define WM_F      SGUI(KC_F)
#define WM_H      LGUI(KC_H)
#define WM_LEFT   LGUI(KC_LEFT)
#define WM_RGHT   LGUI(KC_RGHT)
#define WM_S      LGUI(KC_S)
#define WM_S0     SGUI(KC_F10)
#define WM_S1     SGUI(KC_F1)
#define WM_S2     SGUI(KC_F2)
#define WM_S3     SGUI(KC_F3)
#define WM_S4     SGUI(KC_F4)
#define WM_S5     SGUI(KC_F5)
#define WM_S6     SGUI(KC_F6)
#define WM_S7     SGUI(KC_F7)
#define WM_S8     SGUI(KC_F8)
#define WM_S9     SGUI(KC_F9)
#define WM_SA     SGUI(KC_A)
#define WM_SC     SGUI(KC_C)
#define WM_SDOWN  SGUI(KC_DOWN)
#define WM_SE     SGUI(KC_E)
#define WM_SLEFT  SGUI(KC_LEFT)
#define WM_SPC    LGUI(KC_SPC)
#define WM_SQ     SGUI(KC_Q)
#define WM_SR     SGUI(KC_R)
#define WM_SRGHT  SGUI(KC_RGHT)
#define WM_SSPC   SGUI(KC_SPC)
#define WM_SUP    SGUI(KC_UP)
#define WM_SV     SGUI(KC_V)
#define WM_UP     LGUI(KC_UP)
#define WM_V      LGUI(KC_V)
#define WM_Z      LGUI(KC_Z)
