// Copyright 2025 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono2
//    unicode_glyphs | 
//    output         | tiny-18
//    input          | tiny-18.png

// Glyphs have a size of 20 pixels height x 11 pixel width.

#pragma once

#include <qp.h>

extern const uint32_t font_tiny_18_length;
extern const uint8_t  font_tiny_18[2294];
